services:
  - type: web
    name: password-game
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
